Fix forced ticket not opened when user block PV
RedsTom/TicketTools pull request #20
Opened 2022-12-20 20:27 UTC by enimaloc

## Bug description

When trying force to open a ticket using `!new %id%`, the bot ignores the fact that it can DM you or not, and considers user have received the message anyway.
It then considers the ticket to be opened while it is not.

Related #14 
Fixes #19

2022-12-20 20:42 UTC, RedsTom requested changes

2022-12-20 20:42 UTC, RedsTom commented on src/main/java/yt/graven/gravensupport/commands/ticket/Ticket.java
> +    }
Why using AtomicReferences and Thread.sleep instead of using a CompletableFuture and subscribing to changes (thenApply)

2022-12-20 20:42 UTC, RedsTom commented on src/main/java/yt/graven/gravensupport/commands/ticket/Ticket.java
> +        AtomicReference<IOException>      exception = new AtomicReference<>(null);
Fix code conventions to match those of the project (checkstyle will be added in a near future)

2023-06-23 17:37 UTC, AntoineJT commented
won't do

2023-06-23 17:37 UTC, closed without merging